version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0

jobs:
  check_format_validate:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: .
      - terraform/validate:
          path: .

workflows:
  validate_module:
    jobs:
      - check_format_validate
